### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#11]
Smart sätt att hitta [närliggande platser](https://github.com/dt222cc/1dv450-dt222cc/blob/master/2-api/app/controllers/api/v1/events_controller.rb#L24). Samtidigt hade det varit kul att se (och kanske kunna söka på) ortnamn och sådant. En rekomendation är gemet [geocoder](https://github.com/alexreisner/geocoder) där man väldigt enkelt kan få ut sådan info.

**Comment by dt222cc** [comment]
Har haft funderingar på att implementera det tidigare men det var inget krav så jag körde inte på det. Vi får se om jag ändrar det senare längre fram.
