### ISSUE TITLE
Presentation av objekt

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#12]
När jag gör en get t.ex. av alla events presenteras det tydligt. Särskilt mycket gillar jag att sådant som "amount" presenteras. Behöver man däremot visa sådana egenskaper som "id", "created_at, "updated_at" osv. Sedan hade jag gärna sett alla taggar och kanske platsens koordinater.  

För att styra vad som visas kan man göra som [här](https://github.com/thajo/1dv450_demo/blob/master/app/models/team.rb#L23-L28) eller använda gemet [rabl](http://railscasts.com/episodes/322-rabl).

**Comment by dt222cc** [comment]
Uppdaterad
