### ISSUE TITLE
HATEOAS

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#13]
Enligt kurshemsidan ska api:et grunda sig i [HATEOAS](https://youtu.be/l6OMeZADqWg?t=1h4m47s) där varje request också bär med sig länkar till andra resurser och actions. Exakt hur det skulle implementeras är jag osäker på. Exempel skulle kunna vara att om man hämtar ut ett event finns en länk `api/v1/positions/{position_id}` till dess position. Eller att om man skapar ett event får man en länk till dess show action.

**Comment by dt222cc** [comment]
Implementerad
