### ISSUE TITLE
If not

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#15]
Försök att undvika ["if-not-villkor"](https://github.com/bbatsov/ruby-style-guide#unless-for-negatives). Istället för `if !(tag = Tag.find_by_id(params[:tag_id])).nil?` använd `if tag = Tag.find_by_id(params[:tag_id])`, eller istället för `if !events.present?` använd `unless events.present?`.

**Comment by dt222cc** [comment]
Noterat, tack for feedback. Trevligt med länken :)
