### ISSUE TITLE
Auktorisering update, destroy

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#16]
Är ganska säker på att jag kan redigera event som andra creators skapat. På destroy kontrolleras vem som är eventets creator, men jag försöker ta bort ett event som jag inte är skapare till får jag 404 not found. Kan tycka att man borde få 403 forbidden.

**Comment by dt222cc** [comment]
Åtgärdat, glömde kontrollera/filtrera händelser efter skapare.
