### ISSUE TITLE
Get all events w. tag

### ISSUE THREAD

**Issue by henceee** [dt222cc/1dv450-dt222cc#18]
Get with all events with tag ger 500 internal error:

https://repo-1dv450-dt222cc.c9users.io/api/v1/events?tag_id=1&access_token=BF6STN_TIeaHNM4t8oiBtw

Extracted source (around line #18):

```
  events = Event.where(position_id: params[:position_id])
elsif params[:tag_id]
  if tag = Tag.find_by_id(params[:tag_id]))
    events = tag.events
    # events = tag.events.limit(@limit).offset(@offset).order("created_at DESC")
  else
```

**Comment by dt222cc** [comment]
Åtgärdat, på min sida glömde jag kontrollera efter nil innan jag plockar taggens händelser.

På din sida så hade koden där uppe syntax fel ')' eftersom jag höll på att göra om/testa kod :)
