### ISSUE TITLE
Förstår ej lösningen, men funkar ju.

### ISSUE THREAD

**Issue by henceee** [dt222cc/1dv450-dt222cc#19]
Varför behöver longitude och latitude gå igenom denna behandling, bör man inte bara kunna använda angivna lat och long parametrarna som de är? Det funkade för min del åtminstone.

events_controller
ln. 24 if (nearby_positions = Position.where(latitude: lat - 2..lat + 2, longitude: lng - 2..lng + 2)).nil?

**Comment by dt222cc** [comment]
Ah det är för att ange precisionen.

Som du ser så har jag satt det på plus eller minus 2 eller rättare sagt mellan:

```
Med lat på 10 och lng på 20.

Leta efter platser som har latitude mellan 8 och 12 och longitude mellan 18 och 22.
```
