### ISSUE TITLE
Basic auth.

### ISSUE THREAD

**Issue by henceee** [dt222cc/1dv450-dt222cc#20]
Nackdelar m. basic authorization är att Password skickas flera gånger och cachas i browsern, samt kan enkelt omvandlas till clear text.

Överväg kanske annan sorts auth. såsom authenticate_with_http_token, ifall du kan få det att funka. Jag fick gå en lite annan väg, men ändå liknande där jag kollade ifall en key skickas med, letade efter keyn i applications och se ifall den existerar, och isåfall blir tillhörande creator current_user

 if params[:key].present?
                appkey = Application.find_by(key: params[:key])
                if(appkey.nil?)
                    render status: 401, json: { message: "Incorrect credentials, check your key." }
                else
             ...

**Comment by dt222cc** [comment]
Jag hänger med att basic är inte så säker men jag tror att du har blandat ihop lite grejer själv. [Här](https://github.com/henceee/1dv450-hg222dv/blob/master/reg1dv450/app/controllers/api/api_controller.rb#L33), du begränsar användning av API med API-nyckel såklart med du har på något sätt kopplat ihop Creator med User vilket inte ska gå då de har inga relationer med varandra ,typ.

User är ju en "utvecklare" som registrerar sin applikation som har Creators registrerade på sin applikation. Creator är en resurs ägare som använder applikationen som utvecklaren(User) registrerar i första del. API:et tar emot en respons med api-nyckel(kopplad till en applikation) och vid vissa anrop även en resurs ägares autentiserings uppgifter. Jag körde på Basic eftersom det gick snabbt att implementera det, ska kolla på "jwt". Det verkar som att du saknar en autentisering?
