### ISSUE TITLE
Bakvänd autentisiering

### ISSUE THREAD

**Issue by ehamrin** [dt222cc/1dv450-dt222cc#22]
LoginCtrl.js

Vid error loggas användaren in om HTTP-status är 422 Unprocessable Entity

Läs gärna på om denna [HTTP-status](http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity) och varför den kanske inte passar in här. Statusen borde vara 2XX.

**Comment by dt222cc** [comment]
Svag med autentisering just nu. Det är på grund av en ful lösning (422, kmr inte ihåg vrf jag valde just 422, kanske copy+paste).

Det fungerar så att applikationen försöker skapa en låtsas event med användaruppgifterna. 422 (som bör förmodligen ändras) får man som respons om man försöker skapa en ogiltig event och man kan bara skapa en event ifall inloggningen lyckades. Som sagt detta var en ful-hack då jag orkade inte hoppa in API:et och ändra autentisering och/eller auktorisering.
