### ISSUE TITLE
Saknar användarvänliga meddelanden i flera vyer

### ISSUE THREAD

**Issue by ehamrin** [dt222cc/1dv450-dt222cc#23]
Det är egentligen bara DeleteResourceCtrl.js som använder sig av meddelanden, överväg att lägga flash messages på $rootScope, och plocka in det i alla controllers så kan du ha centraliserade funktioner för att följa DRY och samtidigt få konsekventa meddelanden genom hela applikationen

**Comment by dt222cc** [comment]
Åtgärdat, tack.
