### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by sk222sw** [dt222cc/1dv450-dt222cc#27]
Hej! Fick i uppgift av John att göra en peer review på ditt API. Tycker din kod ser bra ut och har väl ingenting att anmärka där, utifrån mina kunskaper i ruby/rails tycker jag du följer konventioner och du följer DRY. Bra med kommentarer också.

**Här är lite anmärkningar:**
- Ingen användarvänlig 404-sida, utan rails "red screen of death"
- Det saknas instruktioner för hur man söker på ett event i närheten av en position.
- Vad jag kan se har du ingen **dokumentation** eller **kod** som uppfyller detta krav:
  
  > Med hjälp av HTTP-anrop till API:et ska man kunna skriva en sökfråga som söker händelse på lämpligt sätt.
- Någon instruktion för hur man autentiserar sig utan Postman vore bra. Alltså om man bygger en applikation som använder ditt API.
- Jag kan tycka att det är smidigare att jobba med API:t om man har API-nyckeln i en header, så man ser lite enklare på URL:en vad som händer, men det är ingen stor grej.
- Instruktionerna för POST säger att attributen "species, weight och width" ska inkluderas, men det verkar vara fel?
- Jag lyckas inte med POST eller PUT till events. I exemplet för POST har du med latitude/longitude, men i ditt felmeddelande med meddelandet "error": "Parse error: check spelling, etc. Example:" ska man skicka med "address_city", men jag får ingen av dem att funka, utan får bara felmeddelandet

`{
  "error": "Parse error: check spelling, etc. Example:",
  "body": {
    "event": {
      "name": "string, required",
      "description": "string, required",
      "position": {
        "address_city": "string, required"
      },
      "tags": [
        {
          "name": "optional"
        },
        {
          "name": "optional"
        }
      ]
    }
  }
}`

med status 422, Unprocessable Entity

**Comment by dt222cc** [comment]
Hejsan, tack för anmärkningarna.

##### Det saknas instruktioner för hur man söker på ett event i närheten av en position.
- Det står i README filen att man kan använda parameterna `lat` och `lng`. I events-controller.rb 

##### Med hjälp av HTTP-anrop till API:et ska man kunna skriva en sökfråga som söker händelse på lämpligt sätt.
- Det sker med `query` parametern som jag glömde lägga till i README filen. [events-controller.rb, rad 20-23](https://github.com/dt222cc/1dv450-dt222cc/blob/master/2-api/app/controllers/api/v1/events_controller.rb#L20-L23)

#### POST/PUT
- Jag glömde uppdatera texten i API:ets README fil angående uppdatering av positioneringen.
- Körde först med latitude och longitude men API:et har sen dess ändrats till att man använder `address_city`, adressens koordinater hämtas med hjälp av geocoding (geocoder).
- Det bör fungera med en address, t.ex:

```
{
  "event": {
    "name": "POST test",
    "description": "Med address_city, i body'n skickar man med en objekt med en event-objekt",
    "position": {
        "address_city": "Bredbandet 1, 392 30 Kalmar, Sweden"
    },
    "tags": [
      {
        "name": "test"
      }
    ]
  }
}
```
- Dock inte precis fullständig ännu då jag har märkt nu att texten som man matar in i `address_city` förblir som den är (t.ex "Bredbandet 1") då det var tänkt att den skulle egentligen vara den fullständiga adressen (Bredbandet 1, 392 30 Kalmar, Sweden). Det fungerade tidigare med lat & lng hade jag för mig, men inte nu :(
