### ISSUE TITLE
peer-review 

### ISSUE THREAD

**Issue by Marco30** [dt222cc/1dv450-dt222cc#5]
Hej, har gått igenom din registrerings applikation, hat testat allt och alla funktioner funkar som förväntat.  Vad gäller koden så tycker jag att den var enkel att förstå och följa för att du har bra med kommentarer.  Tyckte att det var en bra lösning att åter använda views så att man inte gör en show view för user och en för admin, utan använder samma men utifrån den som är inloggade visar de funktioner den har behörighet till. Själv gjorde jag en för varje vilket kändes bra när jag gjorde det men känns inte så längre.

Har två saker jag kan tänka mig skulle vara bra att implementera.

Den första är att ha direkt valideringen på login formulären, som det är just nu så kan man posta fast textrutorna är tomma. Det hanteras med ett fel meddelande efter man postat men skulle kunna hanteras så fort användaren trycker på post knappen. Läger du till :required => true så får du ett automatiks fel meddelande och inget postas fören användaren fyllt i textrutorna 

```
        <%= f.label :email %>
        <%= f.email_field :email, :required => true, class: "form-control" %>
        <%= f.label :password %>
        <%= f.password_field :password, :required => true, class: "form-control" %>
```

sen hittade jag ett säkerhetshål i applikation som jag själv inte tänkt på i min egen applikation, när man varit inloggad och loggar ut och trycker på tillbaka knappen så tas man till användaren man var in loggad som. Jag tänker mig om en användare loggar ut och sen lämnar datorn utan att lämna sidan eller stänger webbläsaren så kan en annan person komma åt deras user/admin information. 

Jag har hittat en lösningen till det problemet, det är att hindra cachning genom att lägga till följande i ApplicationController och läga till data: {no_turbolink: true} i loggot länken.

Länken

<%= link_to "Log out", logout_path, data: {no_turbolink: true}, class: "nav-link-right" %>

ApplicationController

before_action :no_cache

def no_cache
response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
response.headers["Pragma"] = "no-cache"
response.headers["Expires"] = "Fri, 09 Jan 2004 00:00:00 GMT"
end

hälsingar
Marco

**Comment by dt222cc** [comment]
Tack för lösningarna, åtgärdat :+1:

**Comment by 1dv450** [comment]
:+1:
