### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#7]
Instruktionerna för Cloud9 fungerade bra. Postman-filen var bara att köra genom att klistra in rätt url. Väldigt bra att du också visar vad som händer om man t.ex. postar felaktig data. Fundera dock på om instruktionerna för själva api:et ska vara i själva applikationen istället för här på github. Det riktar sig ju till de utvecklare som har registerat sig.

**Comment by dt222cc** [comment]
Tack, javisst jag kan tänka mig lägga till API-dokumentation i själva applikationen när jag har tid för det :)
