### ISSUE TITLE
If-satser och undantag

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#8]
Det sparar en rad kod att göra en tilldelning i en if-sats som du gör många gånger i dina controllers, t.ex. [här](https://github.com/dt222cc/1dv450-dt222cc/blob/master/2-api/app/controllers/api/v1/events_controller.rb#L65). Men jag tycker att det blir svårare att förstå. 

Jag föredrar användningen av ´find´ istället för ´find_by_id´. Visst, den kommer att kasta ett exception vid fel id. Men genom att ha en funktion som räddar t.ex. alla `RecordNotFound` exceptions minskar både komplexiteten och antalet rader kod. Ett exempel på vad jag menar finns i [den här controllern](https://github.com/thajo/1dv450_demo/blob/master/app/controllers/teams_controller.rb).

**Comment by dt222cc** [comment]
Noterat
