### ISSUE TITLE
Taggar

### ISSUE THREAD

**Issue by ghost** [dt222cc/1dv450-dt222cc#9]
Hanteringen av taggar fungerar bra. Det går att skapa nya, ta bort och uppdatera. Du undviker även dubletter. Det går också att söka med hjälp av en tagg. Dock saknar jag att man ska söka med hjälp av en sökfråga som står på kurshemsidan att man ska ha. 

Sedan hade det varit nice att när ett event presenteras se vilka taggar det har.

**Comment by dt222cc** [comment]
Nu så kan man även använda sig utav query sökningar. Jag letar igenom Event name, description och Tag name som innehåller till exempel `&query=demo`.
